[workspace]
resolver = "2"
members = ["program", "clients/rust", "cli", "examples/kwil"]


[patch.crates-io.curve25519-dalek]
git = "https://github.com/solana-labs/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"

[patch.crates-io.aes-gcm-siv]
git = "https://github.com/RustCrypto/AEADs"
rev = "6105d7a5591aefa646a95d12b5e8d3f55a9214ef"

[workspace.dependencies]
borsh = "^1.5"
num-derive = "^0.4"
num-traits = "^0.2"
shank = "^0.4.2"
solana-program = "~1.18"
solana-client = "~1.18"
spl-associated-token-account = { version = "^3.0", features = ["no-entrypoint"] }
spl-token-2022 = "^3.0"
spl-token-metadata-interface = "^0.3"
thiserror = "^1.0"
assert_matches = "^1.5"
solana-program-test = "~1.18"
solana-sdk = "~1.18"
ed25519-dalek = "*"
libsecp256k1 = "*"
clap = { version = "4.5.4", features = ["derive"] }
tokio = "^1"

